server:
  port: 19292
  tomcat:
    max-swallow-size: 100MB

spring:
  application:
    name: orderTrack
    version: 0.0.1
  profiles:
  #  active: pro
   active: '@surroundings@'

  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT:1433};databaseName=${DATABASE};?serverTimezone=Asia/Shanghai;rewriteBatchedStatements=true;encrypt=false;calcBigDecimalPrecision=true;
#    username: ${DB_USERNAME:sa}
#    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DATABASE}?serverTimezone=UTC&allowMultiQueries=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: myHikarCp

  # Redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000


  # 前后端传输时间相差8小时问题
  jackson:
    time-zone:
      GMT+8
    date-format:
      yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        keep-alive: 60s
    shutdown:
      await-termination: true
      await-termination-period: 30s



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
      update-strategy: NOT_NULL


exception:
  cacheTime: 3600
  url: 1


logging:
  level:
    com.yunyan: DEBUG
    org.springframework.boot.autoconfigure: error
  config: classpath:config/logback-boot.xml


